# Generated by Django 2.1.7 on 2019-04-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_auto_20190423_1628'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Answer',
        ),
    ]
